import { About } from 'components/About';
import { Header } from 'components/Header';
import { Navbar } from 'components/Navbar';
import { Home as HomeWork } from 'components/Home';
import Head from 'next/head';
import { MyWork } from 'components/MyWork';
import { PublicLayout } from 'layout/PublicLayout';
import { Contact } from 'components/Contact';

export default function Home() {
	return (
		<PublicLayout>
			<>
				<Head>
					<title>Create Next App</title>
					<meta
						name='description'
						content='Generated by create next app'
					/>
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<Header name='Javier' role='FullStack JavaScript Developer' />
				<hr />
				<HomeWork />
				<hr />
				<About />
				<hr />
				<MyWork />
				<hr />
				<Contact />
			</>
		</PublicLayout>
	);
}
